modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
# The modid of the mod
modId="portablebeacons" #mandatory
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Portable Beacons" #mandatory
# A text field displayed in the mod UI
authors="CrossVas" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Portable beacons
'''
# Here's another dependency
[[dependencies.portablebeacons]]
    modId="curios"
    mandatory=false
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.2-5.1.6.4,)"
    ordering="AFTER"
    side="BOTH"
